FROM node:16-alpine

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY frontend/ .

EXPOSE 3000

CMD ["npm", "start"]
